name: Mobile

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
    Build_Android:
      runs-on: macos-latest

      steps:
      - uses: actions/checkout@v1

      - name: Restore NuGet 
        run: |
          nuget restore
          
      - name: Build Android App
        run: |                    
          msbuild ./AutoCompleteSample.Android/AutoCompleteSample.Android.csproj /verbosity:normal /p:Configuration=Release     
